language: cpp

sudo: false

services:
  - docker

before_install:
  - docker pull hkdaq/triggerapplication:base

install: true

script: 
  - docker run --rm -v `pwd`:/root/buildtest hkdaq/triggerapplication:base /bin/sh -c " cd /root/buildtest ; ln -s /TtriggerApplicaiton/ToolDAQ ./ToolDAQ ; source ./Setup.sh ; make clean; make update; make "


