language: cpp

sudo: false

services:
  - docker

before_install:
  - docker pull hkdaq/triggerapplication:base

install: true

script: 
  - docker run --rm -v `pwd`:/root/buildtest hkdaq/triggerapplication:base /bin/sh -c "cd /root/HyperK/ ; source env-WCSim.sh ; cd WCSim ; git pull ;make clean; make rootcint; make; cd /root/buildtest ; ln -s /TriggerApplication/ToolDAQ ./ToolDAQ ; source ./Setup.sh ; make clean; make update; make "


