name: Docker Image CI

on: 
  push:
    branches:
    - Citest
      
jobs:
  container:
    runs-on: ubuntu-latest
    container: docker://hkdaq/triggerapplication:base
    steps:
      - run:|
        ls ./ -al
        cd TriggerApplication; ls ./ -al
        pwd
        echo test
        ls /etc/*release*
          
